runtime: python38
entrypoint: uvicorn challenge.api:app --port 8000

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1
  target_throughput_utilization: 0.6
