name: 'Continuous Integration'

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.19
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.19
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt
      - name: Test API
        run: make api-test
      - name: Test model
        run: make model-test
      - name: Stress test
        run: make stress-test
