name: 'Continuous Integration'

on:
  push:
    branches:
      - main
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - release/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Test API
        run: make api-test
      - name: Test model
        run: make model-test
      - name: Stress test
        run: make stress-test
